chore: update init script

diff --git a/2023/init b/2023/init
--- a/2023/init
+++ b/2023/init
@@ -2,30 +2,42 @@
 
 set -eu -o pipefail
 
-if (( $# != 1 )); then
-  echo "error: expected exactly one argument" >&2
+if (( $# < 1 )); then
+  echo "error: expected at least one argument" >&2
   exit 1
 fi
+
+force=false
+
+while getopts ":f" arg "$@"; do
+  case "$arg" in
+    f) force=true;;
+    *) echo "unknown option: -$OPTARG" >&2; exit 1;;
+  esac
+done
+shift $((OPTIND - 1))
 
 daynum="$(printf "%02d" "$1")"
 dirname="$daynum"
 modname="$(printf "nikc.org/aoc2023/%s" "$daynum")"
 
-if [[ -d "$dirname" ]]; then
+if [[ -d "$dirname" ]] && ! $force; then
   echo "error: directory $dirname already exists" >&2
   exit 1
 fi
 
-mkdir -p "$dirname" && cd "$_" && go mod init "$modname" && touch input.txt input_test.txt && { \
-cat > main.go <<EOT
+mkdir -p "$dirname" && cd "$_" && { go mod init "$modname" || true; } && touch input.txt input_test.txt && { \
+cat <<EOT
 package main
 
 import (
+  "bufio"
   _ "embed"
   "errors"
   "fmt"
   "io"
   "os"
+  "strings"
 )
 
 var (
@@ -40,11 +52,33 @@ func main() {
 }
 
 func mainWithErr(out io.Writer, input string) error {
+  first := solveFirst(input)
+  second := solveSecond(input)
+
   fmt.Fprint(out, "=====[ Day $daynum ]=====\n")
-  return errors.New("not implemented")
+  fmt.Fprintf(out, "first: %d\n", first)
+  fmt.Fprintf(out, "second: %d\n", second)
+
+  return nil
+}
+
+func parseInput(i string) {
+  s := bufio.NewScanner(strings.NewReader(i))
+  for s.Scan() {
+    fmt.Println(s.Text())
+  }
+  panic(errors.New("not implemented"))
+}
+
+func solveFirst(i string) int {
+  return 0
+}
+
+func solveSecond(i string) int {
+  return 0
 }
 EOT
-} && { cat > main_test.go <<'EOT'
+} > main.go && { cat <<EOT
 package main
 
 import (
@@ -62,6 +96,20 @@ var (
 func TestMainWithErr(t *testing.T) {
   assert.NoError(t, mainWithErr(&bytes.Buffer{}, testInput))
 }
+
+func TestParseInput(t *testing.T) {
+  parseInput(testInput)
+}
+
+func TestSolveFirst(t *testing.T) {
+  sol := solveFirst(testInput)
+  assert.Equal(t, ${2:-0}, sol)
+}
+
+func TestSolveSecond(t *testing.T) {
+  sol := solveSecond(testInput)
+  assert.Equal(t, 0, sol)
+}
 EOT
-} && go fmt ./*.go && cd .. && go work use "./$daynum" && go work sync
+} > main_test.go && go fmt ./*.go && cd .. && go work use "./$daynum" && go work sync
 
